# Generated by Django 6.0.5 on 2026-05-21 22:04

import functools

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
import django.utils.crypto
from django.conf import settings
from django.db import migrations, models

import asu.core.models.base


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.UUID7(),
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="date created",
                    ),
                ),
                (
                    "updated_at",
                    asu.core.models.base.AutoUpdatedField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name="date updated",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "code",
                    models.CharField(
                        default=functools.partial(
                            django.utils.crypto.get_random_string,
                            allowed_chars="0123456789",
                            length=6,
                        ),
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Please enter a valid code.", regex="^\\d{6}$"
                            )
                        ],
                        verbose_name="code",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date verified"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date completed"
                    ),
                ),
                (
                    "nulled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DB_SET_NULL,
                        to="verification.passwordresetverification",
                        verbose_name="nulled by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DB_CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "password reset verification",
                "verbose_name_plural": "password reset verifications",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.UUID7(),
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="date created",
                    ),
                ),
                (
                    "updated_at",
                    asu.core.models.base.AutoUpdatedField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name="date updated",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "code",
                    models.CharField(
                        default=functools.partial(
                            django.utils.crypto.get_random_string,
                            allowed_chars="0123456789",
                            length=6,
                        ),
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Please enter a valid code.", regex="^\\d{6}$"
                            )
                        ],
                        verbose_name="code",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date verified"
                    ),
                ),
                (
                    "nulled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DB_SET_NULL,
                        to="verification.emailverification",
                        verbose_name="nulled by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DB_CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "email verification",
                "verbose_name_plural": "email verifications",
                "abstract": False,
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Upper("email"),
                        name="email_verification_email_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RegistrationVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.UUID7(),
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="date created",
                    ),
                ),
                (
                    "updated_at",
                    asu.core.models.base.AutoUpdatedField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name="date updated",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "code",
                    models.CharField(
                        default=functools.partial(
                            django.utils.crypto.get_random_string,
                            allowed_chars="0123456789",
                            length=6,
                        ),
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Please enter a valid code.", regex="^\\d{6}$"
                            )
                        ],
                        verbose_name="code",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date verified"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date completed"
                    ),
                ),
                (
                    "nulled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DB_SET_NULL,
                        to="verification.registrationverification",
                        verbose_name="nulled by",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DB_SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "registration verification",
                "verbose_name_plural": "registration verifications",
                "abstract": False,
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Upper("email"),
                        name="registration_email_idx",
                    )
                ],
            },
        ),
    ]
