volumes:
  rabbitmq-data:

services:
  rabbitmq:
    container_name: asu-rabbitmq
    image: rabbitmq:4.2.6@sha256:0f0eeaba114a94a9e4aae6a5bde40de85e0ab3b9ae7fe715a25cac19c4253643
    hostname: rabbitmq-local
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  celery-worker: &celery
    container_name: asu-celery-worker
    command: watchfiles --filter python "celery worker --loglevel INFO --autoscale=4,0"
    depends_on:
      - rabbitmq
    extends:
      file: common.yml
      service: python

  celery-beat:
    <<: *celery
    container_name: asu-celery-beat
    command: celery beat --loglevel INFO
