# Generated by Django 6.0.5 on 2026-05-21 22:30

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

import asu.auth.models.user
import asu.core.models.base
import asu.core.utils.file


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.UUID7(),
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="date created",
                    ),
                ),
                (
                    "updated_at",
                    asu.core.models.base.AutoUpdatedField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name="date updated",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            asu.auth.models.user.UsernameValidator(),
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=32, verbose_name="display name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        validators=[django.core.validators.MaxLengthValidator(140)],
                        verbose_name="description",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="e-mail"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="birth date"),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        upload_to=asu.core.utils.file.UserContentPath(
                            "{instance.pk}/profile_picture/{uuid}{ext}"
                        ),
                        validators=[
                            asu.core.utils.file.FileSizeValidator(max_size=2097152),
                            asu.core.utils.file.MimeTypeValidator(
                                allowed_types=["image/png", "image/jpeg"]
                            ),
                        ],
                        verbose_name="profile picture",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("tr", "Turkish")],
                        default="en",
                        max_length=8,
                        verbose_name="language",
                    ),
                ),
                (
                    "allows_receipts",
                    models.BooleanField(
                        default=True, verbose_name="allows message receipts"
                    ),
                ),
                (
                    "allows_all_messages",
                    models.BooleanField(
                        default=True,
                        help_text="Users that are not followed by this user can send message requests to them.",
                        verbose_name="allows all incoming messages",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_frozen",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this user has frozen their account.",
                        verbose_name="frozen",
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=False,
                        help_text="Private profiles are only visible to approved followers.",
                        verbose_name="private",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
            managers=[
                ("objects", asu.auth.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "session_key",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="session key",
                    ),
                ),
                ("session_data", models.TextField(verbose_name="session data")),
                (
                    "expire_date",
                    models.DateTimeField(db_index=True, verbose_name="expire date"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="ip address"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.UUID7(),
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="date created",
                    ),
                ),
                (
                    "updated_at",
                    asu.core.models.base.AutoUpdatedField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name="date updated",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="user",
            name="blocked",
            field=models.ManyToManyField(
                blank=True,
                related_name="blocked_by",
                through="account.UserBlock",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UserDeactivation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.UUID7(),
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="date created",
                    ),
                ),
                (
                    "updated_at",
                    asu.core.models.base.AutoUpdatedField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name="date updated",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date revoked"
                    ),
                ),
                (
                    "for_deletion",
                    models.BooleanField(
                        default=False,
                        help_text="Marks this user for permanent deletion.",
                        verbose_name="for deletion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deactivations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user deactivation",
                "verbose_name_plural": "user deactivations",
            },
        ),
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.UUID7(),
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="date created",
                    ),
                ),
                (
                    "updated_at",
                    asu.core.models.base.AutoUpdatedField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name="date updated",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                related_name="followed_by",
                through="account.UserFollow",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UserFollowRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=django.db.models.functions.UUID7(),
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="date created",
                    ),
                ),
                (
                    "updated_at",
                    asu.core.models.base.AutoUpdatedField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name="date updated",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                        ],
                        default="pending",
                        max_length=8,
                        verbose_name="status",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="userblock",
            constraint=models.UniqueConstraint(
                fields=("from_user", "to_user"), name="unique_account_userblock"
            ),
        ),
        migrations.AddConstraint(
            model_name="userdeactivation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("user",),
                name="unique_pending_user_deactivation",
            ),
        ),
        migrations.AddConstraint(
            model_name="userfollow",
            constraint=models.UniqueConstraint(
                fields=("from_user", "to_user"), name="unique_account_userfollow"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("username__regex", "^[a-zA-Z0-9]+(_[a-zA-Z0-9]+)*$")
                ),
                name="regex_valid_username",
                violation_error_message="Usernames can only contain latin letters, numerals and underscores. Trailing, leading or consecutive underscores are not allowed.",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("username"),
                name="unique_ci_username",
                violation_error_message="The username you specified is already in use.",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("email"),
                name="unique_ci_email",
                violation_error_message="This e-mail is not usable.",
            ),
        ),
        migrations.AddIndex(
            model_name="userfollowrequest",
            index=models.Index(
                fields=["status", "from_user", "to_user"],
                name="follow_request_frequents",
            ),
        ),
        migrations.AddConstraint(
            model_name="userfollowrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("from_user", "to_user"),
                name="unique_user_follow_request",
            ),
        ),
    ]
