# Generated by Django 4.2 on 2023-05-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "session_key",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="session key",
                    ),
                ),
                ("session_data", models.TextField(verbose_name="session data")),
                (
                    "expire_date",
                    models.DateTimeField(db_index=True, verbose_name="expire date"),
                ),
                (
                    "user",
                    models.BigIntegerField(blank=True, null=True, verbose_name="user"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="ip address"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["user"], name="account_ses_user_941a72_idx"),
        ),
    ]
