# Generated by Django 6.0.5 on 2026-05-21 22:39

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_oauth2"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("oauth2_provider", "0013_alter_application_authorization_grant_type_device"),
        ("otp_static", "0003_add_timestamps"),
        ("otp_totp", "0003_add_timestamps"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessToken",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("oauth2_provider.accesstoken",),
        ),
        migrations.CreateModel(
            name="Grant",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("oauth2_provider.grant",),
        ),
        migrations.CreateModel(
            name="Group",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.permission",),
            managers=[
                ("objects", django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("oauth2_provider.refreshtoken",),
        ),
        migrations.CreateModel(
            name="StaticDevice",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("otp_static.staticdevice",),
        ),
        migrations.CreateModel(
            name="TOTPDevice",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("otp_totp.totpdevice",),
        ),
    ]
