# Generated by Django 4.2.2 on 2023-08-18 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_application_post_logout_redirect_uris"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDeactivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_revoked",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date revoked"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, verbose_name="date modified"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "account deactivation",
                "verbose_name_plural": "account deactivations",
            },
        ),
        migrations.AddConstraint(
            model_name="userdeactivation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("date_revoked__isnull", True)),
                fields=("user",),
                name="unique_pending_user_deactivation",
            ),
        ),
    ]
