# Generated by Django 4.2.7 on 2023-12-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_rename_user_constraints"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userfollowrequest",
            index=models.Index(
                fields=["status", "from_user", "to_user"],
                name="follow_request_frequents",
            ),
        ),
    ]
