# Generated by Django 4.2.7 on 2023-12-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_userfollowrequest_follow_request_frequents"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("tr", "Turkish")],
                default="en",
                max_length=8,
                verbose_name="language",
            ),
        ),
    ]
