# Generated by Django 4.2.16 on 2024-10-03 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("otp_static", "0003_add_timestamps"),
        ("otp_totp", "0003_add_timestamps"),
        ("oauth2_provider", "0012_add_token_checksum"),
        ("account", "0011_application_allowed_origins_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessToken",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("oauth2_provider.accesstoken",),
        ),
        migrations.CreateModel(
            name="Grant",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("oauth2_provider.grant",),
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("oauth2_provider.refreshtoken",),
        ),
        migrations.CreateModel(
            name="StaticDevice",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("otp_static.staticdevice",),
        ),
        migrations.CreateModel(
            name="TOTPDevice",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("otp_totp.totpdevice",),
        ),
    ]
