# Generated by Django 4.0.1 on 2022-07-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeynep_auth', '0006_user_allows_all_messages_user_allows_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='profile picture'),
        ),
    ]
