# Generated by Django 6.0.5 on 2026-05-21 22:04

import django.db.models.functions.datetime
from django.db import migrations, models

import asu.core.models.base


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectVariable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=asu.core.models.base.UUIDv7(),
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        verbose_name="date created",
                    ),
                ),
                (
                    "updated_at",
                    asu.core.models.base.AutoUpdatedField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                        verbose_name="date updated",
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="name")),
                ("value", models.JSONField(verbose_name="value")),
            ],
            options={
                "verbose_name": "project variable",
                "verbose_name_plural": "project variables",
            },
        ),
    ]
