# Generated by Django 4.0.1 on 2022-01-16 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('code', models.CharField(max_length=6, verbose_name='code')),
                ('date_verified', models.DateTimeField(blank=True, null=True, verbose_name='date verified')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'registration verification',
                'verbose_name_plural': 'registration verifications',
            },
        ),
    ]
