# Generated by Django 4.0.1 on 2022-03-11 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "verification",
            "0007_passwordresetverification_date_completed_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="nulled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="verification.emailverification",
                verbose_name="nulled by",
            ),
        ),
        migrations.AddField(
            model_name="passwordresetverification",
            name="nulled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="verification.passwordresetverification",
                verbose_name="nulled by",
            ),
        ),
        migrations.AddField(
            model_name="registrationverification",
            name="nulled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="verification.registrationverification",
                verbose_name="nulled by",
            ),
        ),
    ]
