# Generated by Django 4.2.9 on 2024-01-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["date_modified"], name="messaging_c_date_mo_534b03_idx"
            ),
        ),
    ]
