# Generated by Django 4.2.16 on 2024-10-03 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_orphan_messages_trigger"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interaction",
            name="event",
        ),
        migrations.AddField(
            model_name="interaction",
            name="message",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="messaging.message",
                verbose_name="message",
            ),
            preserve_default=False,
        ),
    ]
