# Generated by Django 4.2.9 on 2024-02-26 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_conversation_modified_index"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE
                OR REPLACE FUNCTION delete_orphan_message()
                RETURNS TRIGGER
                LANGUAGE plpgsql AS
            $$
            BEGIN
                -- When a message assignment gets deleted, check if any other
                -- assignments remain to that given message. If not, delete the
                -- message itself.
                DELETE
                FROM messaging_message message
                WHERE message.id = OLD.message_id
                  AND NOT EXISTS(SELECT 1
                                 FROM messaging_conversation_messages
                                 WHERE message_id = OLD.message_id);
                RETURN NULL;
            END;
            $$;

            CREATE
                OR REPLACE TRIGGER delete_orphan_messages
                AFTER DELETE
                ON messaging_conversation_messages
                FOR EACH ROW
            EXECUTE FUNCTION delete_orphan_message();
            """,
            reverse_sql="DROP FUNCTION IF EXISTS delete_orphan_message CASCADE;",
        )
    ]
