# Generated by Django 4.2.14 on 2024-08-28 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messaging", "0003_orphan_message_trigger"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("message", "message")],
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
            ],
            options={
                "verbose_name": "conversation event",
                "verbose_name_plural": "conversation events",
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "participation",
                "verbose_name_plural": "participations",
            },
        ),
        migrations.RemoveConstraint(
            model_name="conversation",
            name="unique_conversation",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="messages",
        ),
        migrations.RemoveField(
            model_name="message",
            name="recipient",
        ),
        migrations.AddField(
            model_name="conversation",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="conversation",
            name="is_group",
            field=models.BooleanField(default=False, verbose_name="group"),
        ),
        migrations.AddField(
            model_name="conversation",
            name="name",
            field=models.CharField(blank=True, max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="holder",
            field=models.ForeignKey(
                help_text="In private conversations, this field holds one of the participants. In group conversations, this field holds the creator of the conversation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="holder",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="target",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="targeted_conversations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="target",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_group", False)),
                fields=("holder", "target"),
                name="unique_private_conversation",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.CheckConstraint(
                check=models.Case(
                    models.When(
                        is_group=False,
                        then=models.Q(
                            ("holder__isnull", False), ("target__isnull", False)
                        ),
                    ),
                    models.When(
                        is_group=True,
                        then=models.Q(
                            ("holder__isnull", False), ("target__isnull", True)
                        ),
                    ),
                    default=False,
                    output_field=models.BooleanField(),
                ),
                name="valid_private_conversation",
                violation_error_message="Private conversations must have valid holder and target fields.",
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="messaging.conversation",
                verbose_name="conversation",
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="messaging.conversation",
                verbose_name="conversation",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="messaging.message",
                verbose_name="message",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                through="messaging.Participation",
                to=settings.AUTH_USER_MODEL,
                verbose_name="participants",
            ),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                fields=("user", "conversation"), name="unique_participation"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", "message")),
                fields=("conversation", "message"),
                name="unique_conversation_message",
            ),
        ),
    ]
