# Generated by Django 4.0.1 on 2022-01-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zaida_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                default="", max_length=32, verbose_name="display name"
            ),
            preserve_default=False,
        ),
    ]
