# Generated by Django 4.0.1 on 2022-01-16 19:26

from django.db import migrations, models
import zaida.verification.models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationverification",
            name="code",
            field=models.CharField(
                max_length=6,
                validators=[zaida.verification.models.base.code_validator],
                verbose_name="code",
            ),
        ),
        migrations.AddConstraint(
            model_name="registrationverification",
            constraint=models.UniqueConstraint(
                fields=("email", "code"), name="unique_email_and_code"
            ),
        ),
    ]
