apiVersion: batch/v1
kind: Job
metadata:
  name: django-collectstatic
spec:
  template:
    spec:
      containers:
        - name: django-collectstatic
          image: docker.io/library/asu-python:latest
          command: [ "python",  "manage.py", "collectstatic", "--noinput" ]
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: asu-secrets
            - secretRef:
                name: postgres-secrets
      restartPolicy: Never
  backoffLimit: 3
