# Generated by Django 4.0.1 on 2022-07-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationrequest',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='conversationrequest',
            name='date_accepted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_accepted'),
        ),
    ]
