# Generated by Django 4.0.1 on 2022-07-14 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0002_remove_conversationrequest_is_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversationrequest',
            name='unique_conversation_request',
        ),
        migrations.RemoveField(
            model_name='conversationrequest',
            name='conversation',
        ),
        migrations.AddField(
            model_name='conversationrequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='messages',
            field=models.ManyToManyField(related_name='conversations', to='messaging.Message'),
        ),
        migrations.AddConstraint(
            model_name='conversationrequest',
            constraint=models.UniqueConstraint(fields=('sender', 'recipient'), name='unique_conversation_request'),
        ),
    ]
